### ISSUE TITLE
TypeError: RequestInit: duplex option is required when sending a body.

### ISSUE THREAD

**Issue by aurel282** [ipfs/js-ipfs-utils#249]
Updating to node v18.14.0
NPM: 9.4.2

I have this error when pushing files to IPFS

error - TypeError: RequestInit: duplex option is required when sending a body.

 at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.fetch (/node_modules/ipfs-utils/src/http.js:132:22)
    at async Object.addAll (/node_modules/ipfs-http-client/src/add-all.js:36:17)
    at async handler (webpack-internal:///(api)/./src/pages/api/sendToIPFS.ts:35:22)

**Comment by laciferin2024** [comment]
Thanks . Really saved my day
