### ISSUE TITLE
Identifier 'global' has already been declared when run with jest

### ISSUE THREAD

**Issue by bluelovers** [ipfs/js-ipfs-utils#29]
```ts
import useIPFS, { ICachedObject } from 'use-ipfs';
import { IIPFSPromiseApi } from 'ipfs-types';
import checkAll from '../index';

it('check local', async () =>
{
	return useIPFS({
		disposable: true,
	})
		.then(async ({
			ipfs,
			ipfsType,
			stop,
			ipfsd,
		}: ICachedObject<IIPFSPromiseApi>) => {

			let ret = await checkAll(ipfs)

			expect(ret).toMatchSnapshot();

			return stop();
		})
	;
});
```

```
  ● Test suite failed to run

    node_modules\ipfs-utils\src\http.js:7
    const global = require('./globalthis')
          ^

    SyntaxError: Identifier 'global' has already been declared

      at Runtime._execModule (../../node_modules/jest-runtime/build/index.js:1009:58)
      at Object.<anonymous> (../../node_modules/ipfs-utils/src/files/url-source.js:3:14)
```

**Comment by bluelovers** [comment]
but i think better way is remove `globalthis.js`, 

let build tool handle it, no need do it in this project

**Comment by lidel** [comment]
For the record, I've hit the same problem when trying to update [ipfs-redux-bundle](https://github.com/ipfs-shipyard/ipfs-redux-bundle) to ipfs-http-client v43.0.0

**Comment by bluelovers** [comment]
https://github.com/ipfs/js-ipfs-utils/pull/30

**Comment by bluelovers** [comment]
@lidel this is how i get ipfs in react

https://github.com/bluelovers/ipfs-web-upload/blob/master/src/lib/ipfs/setupIPFS.ts
