### ISSUE TITLE
Building docs fails during release

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs-utils#99]
```
[13:23:33] Generating documentation [started]
Loaded plugin /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/aegir/src/ts/typedoc-plugin.js

Using TypeScript 4.1.3 from /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typescript/lib
Warning: You are running in an unsupported TypeScript version! TypeDoc supports 3.9.x || 4.0.x
/Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/context.js:56
            throw new Error(`Expected a symbol for node with kind ${ts.SyntaxKind[node.kind]}`);
            ^

Error: Expected a symbol for node with kind Identifier
    at Context.expectSymbolAtLocation (/Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/context.js:56:19)
    at /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/nodes/export.js:79:69
    at Array.forEach (<anonymous>)
    at ExportDeclarationConverter.convert (/Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/nodes/export.js:76:40)
    at Converter.convertNode (/Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/converter.js:117:53)
    at /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/nodes/block.js:66:28
    at Array.forEach (<anonymous>)
    at BlockConverter.convertStatements (/Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/nodes/block.js:65:24)
    at BlockConverter.convert (/Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/nodes/block.js:34:18)
    at Converter.convertNode (/Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/typedoc/dist/lib/converter/converter.js:117:53)
[13:23:37] Generating documentation [failed]
[13:23:37] → Command failed with exit code 1: typedoc --inputfiles /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/dist --mode modules --out docs --excludeExternals --includeDeclarations --hideGenerator --includeVersion --gitRevision master --disableSources --plugin /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/aegir/src/ts/typedoc-plugin.js --theme /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/aegir-typedoc-theme/bin/default
[13:23:37] Publish documentation [failed]
[13:23:37] → Command failed with exit code 1: typedoc --inputfiles /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/dist --mode modules --out docs --excludeExternals --includeDeclarations --hideGenerator --includeVersion --gitRevision master --disableSources --plugin /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/aegir/src/ts/typedoc-plugin.js --theme /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/aegir-typedoc-theme/bin/default
Command failed with exit code 1: typedoc --inputfiles /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/dist --mode modules --out docs --excludeExternals --includeDeclarations --hideGenerator --includeVersion --gitRevision master --disableSources --plugin /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/aegir/src/ts/typedoc-plugin.js --theme /Users/alex/Documents/Workspaces/ipfs/js-ipfs-utils/node_modules/aegir-typedoc-theme/bin/default
```

**Comment by achingbrain** [comment]
This is still broken.

**Comment by hugomrdias** [comment]
its in the latest release
